gsm/gsm/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("users.urls")),
    path('index/', include("users.urls")),
    path('blog/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),

]

gsm/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from markdownx.models import MarkdownxField
from markdownx.utils import markdown

# Create your models here.


class User(AbstractUser):
    name = models.CharField(max_length=60)
    jum = models.IntegerField(default=0)


class Category(models.Model):
    name = models.CharField(max_length=25, unique=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True, allow_unicode=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return '/blog/category/{}/'.format(self.slug)
    class Meta:
        verbose_name_plural = 'categories'


class Tag(models.Model):
    name = models.CharField(max_length=40, unique=True)
    slug = models.SlugField(unique=True, allow_unicode=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return '/blog/tag/{}/'.format(self.slug)

class Post(models.Model):
    title = models.CharField(max_length=30)
    content = MarkdownxField()
    head_image = models.ImageField(upload_to='blog/%Y/%m/%d/', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag, blank=True)
    def __str__(self):
        return '{} :: {}'.format(self.title, self.author)
    def get_absolute_url(self):
        return '/blog/{}/'.format(self.pk)
    def get_update_url(self):
        return self.get_absolute_url() + 'update/'
    def get_markdown_content(self):
        return markdown(self.content)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = MarkdownxField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def get_markdown_content(self):
        return markdown(self.text)

    def get_absolute_url(self):
        return self.post.get_absolute_url() + '#comment-id-{}'.format(self.pk)

gsm/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} 오늘 뭐 볼까? 자유게시판{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/_assets/css/custom.min.css' %}">

</head>
<body>

<div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary" id="navbar">
    <div class="container">
        <a href="../" class="navbar-brand">오늘 뭐 볼까? 자유게시판</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Themes <span class="caret"></span></a>
                    <div class="dropdown-menu" aria-labelledby="themes">
                        <a class="dropdown-item" href="../default/">Default</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="../cerulean/">Cerulean</a>
                        <a class="dropdown-item" href="../cosmo/">Cosmo</a>
                        <a class="dropdown-item" href="../cyborg/">Cyborg</a>
                        <a class="dropdown-item" href="../darkly/">Darkly</a>
                        <a class="dropdown-item" href="../flatly/">Flatly</a>
                        <a class="dropdown-item" href="../journal/">Journal</a>
                        <a class="dropdown-item" href="../litera/">Litera</a>
                        <a class="dropdown-item" href="../lumen/">Lumen</a>
                        <a class="dropdown-item" href="../lux/">Lux</a>
                        <a class="dropdown-item" href="../materia/">Materia</a>
                        <a class="dropdown-item" href="../minty/">Minty</a>
                        <a class="dropdown-item" href="../pulse/">Pulse</a>
                        <a class="dropdown-item" href="../sandstone/">Sandstone</a>
                        <a class="dropdown-item" href="../simplex/">Simplex</a>
                        <a class="dropdown-item" href="../sketchy/">Sketchy</a>
                        <a class="dropdown-item" href="../slate/">Slate</a>
                        <a class="dropdown-item" href="../solar/">Solar</a>
                        <a class="dropdown-item" href="../spacelab/">Spacelab</a>
                        <a class="dropdown-item" href="../superhero/">Superhero</a>
                        <a class="dropdown-item" href="../united/">United</a>
                        <a class="dropdown-item" href="../yeti/">Yeti</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="../blog/">Main</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about_me/">About me</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Litera <span class="caret"></span></a>
                    <div class="dropdown-menu" aria-labelledby="download">
                        <a class="dropdown-item" rel="noopener" target="_blank" href="https://jsfiddle.net/bootswatch/rnjfzjjo/">Open in JSFiddle</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="../4/litera/bootstrap.min.css" download>bootstrap.min.css</a>
                        <a class="dropdown-item" href="../4/litera/bootstrap.css" download>bootstrap.css</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="../4/litera/_variables.scss" download>_variables.scss</a>
                        <a class="dropdown-item" href="../4/litera/_bootswatch.scss" download>_bootswatch.scss</a>
                    </div>
                </li>
            </ul>

            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="https://wrapbootstrap.com/?rel=bsw" target="_blank">Backend</a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="container" id="main-div">

    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">
            {% block content%}
            {% endblock %}
        </div>

        <!--            &lt;!&ndash; Pagination &ndash;&gt;-->
        <!--            <ul class="pagination justify-content-center mb-4">-->
        <!--                <li class="page-item">-->
        <!--                    <a class="page-link" href="#">&larr; Older</a>-->
        <!--                </li>-->
        <!--                <li class="page-item disabled">-->
        <!--                    <a class="page-link" href="#">Newer &rarr;</a>-->
        <!--                </li>-->
        <!--            </ul>-->

    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4" id="side-div">

        <!-- Search Widget -->
        <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
                </div>
            </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4" id="category-card">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled mb-0">

                            {% for category in category_list %}
                            <li>
                                <a href="{{ category.get_absolute_url }}">{{ category.name }} ({{ category.post_set.count }})</a>
                            </li>
                            {% endfor %}
                            <li>
                                <a href="#">문의/건의</a>
                            </li>
                             <li>
                                <a href="/blog/category/_none/">미분류 ({{ posts_without_category }})</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.row -->

</div>

<script src="{% static 'blog/_assets/js/jquery.min.js' %}"></script>
<script src="{% static 'blog/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'blog/_assets/js/custom.js' %}"></script>

</body>
</html>

gsm/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% load crispy_forms_tags %}

{% block title %}{{ object.title }} -오늘 뭐 볼까? 자유게시판{% endblock %}

{% block content %}
<!-- Title -->
<h1>{{ object.title }}</h1>
{% if object.category %}
<span class="badge rounded-pill bg-warning text-dark float-right">{{ object.category }}</span>
{% else %}
<span class="badge rounded-pill bg-secondary float-right">미분류</span>
{% endif %}

<!-- Author -->
<p class="lead">
    by
    <a href="#">{{ object.author.username }}</a>
</p>
{% if request.user == object.author %}
    <button type="button" class="btn btn-sm btn-outline-danger float-right" onclick="location.href='{{ object.get_update_url }}'">EDIT</button>
{% endif %}
<hr>

<!-- Date/Time -->
<p>Posted on {{ object.created }}</p>
<hr>

<!-- Preview Image -->
{% if object.head_image %}
<img class="img-fluid rounded" src="{{ object.head_image.url }}" alt="{{ object.title }}">
{% endif %}

<!-- Post Content -->
{{ object.get_markdown_content | safe }}
<br/>
<br/>
{% for tag in object.tags.all %}
    <a href="{{ tag.get_absolute_url }}">#{{ tag }}</a>
{% endfor %}
<hr>

<!-- Comments Form -->
<div class="card my-4">
    <h5 class="card-header">Leave a Comment:</h5>
    <div class="card-body">
        <form method="post" action="{{ object.get_absolute_url }}new_comment/">{% csrf_token %}
            <div class="form-group">
                {{ comment_form | crispy }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

<div id="comment-list">
    <!-- Single Comment -->
    {% for comment in object.comment_set.all %}
    <div class="media mb-4" id="comment-id-{{ comment.pk }}">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
             {% if comment.author == request.user %}
                <button class="btn btn-sm btn-outline-danger float-right">delete</button>
                <button class="btn btn-sm btn-outline-success float-right">edit</button>
             {% endif %}
             <h5 class="mt-0">{{ comment.author }} <small class="text-muted">{{ comment.created_at }}</small> </h5>
             {{ comment.get_markdown_content | safe }}
        </div>
    </div>
    {% endfor %}
</div>

<!-- Comment with nested comments -->
<div class="media mb-4">
    <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
    <div class="media-body">
        <h5 class="mt-0">Commenter Name</h5>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
        </div>
        <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
        </div>
    </div>
</div>
{% endblock %}

gsm/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block title %}{{ object.title }} -오늘 뭐 볼까? 자유게시판{% endblock %}

{% block content %}

    <form method="post">{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-info float-right">Submit</button>
    </form>

    {{ form.media }}
{% endblock %}

gsm/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <button type="button" class="btn btn-sm btn-outline-warning float-right" onclick="location.href='/blog/create/'">New Post</button>
{% endif %}

<h1 id="blog-list-title">
    자유게시판
    {% if category %}<small class="text-muted"> : {{ category }}</small>{% endif %}
    {% if tag %}<small class="text-muted"> : #{{ tag }}</small>{% endif %}
</h1>
{% if object_list.exists %}
{% for p in object_list %}
<!-- Blog Post -->
<div class="card mb-4" id="post-card-{{ p.pk }}">
    {% if p.head_image %}
    <img class="card-img-top" src="{{ p.head_image.url }}" alt="Card image cap">
    {% else %}
    <img class="card-img-top" src="https://picsum.photos/700/300/?random" alt="Card image cap">
    {% endif %}

    <div class="card-body">
        {% if p.category %}
        <span class="badge rounded-pill bg-warning text-dark float-right">{{ p.category }}</span>
        {% else %}
        <span class="badge rounded-pill bg-secondary float-right">미분류</span>
        {% endif %}
        <h2 class="card-title">{{ p.title }}</h2>
        <p class="card-text">{{ p.content | truncatewords:50 }}</p>

        {% for tag in p.tags.all %}
        <a href="{{ tag.get_absolute_url }}">#{{ tag }} </a>
        {% endfor %}
        <br/>
        <br/>

        <a href="{{ p.get_absolute_url }}" class="btn btn-primary" id="read-more-post-{{ p.pk }}">Read More &rarr;</a>
    </div>
    <div class="card-footer text-muted">
        Posted on {{ p.created }} by
        <a href="#">{{ p.author }}</a>
    </div>
</div>
{% endfor %}
{% else %}
<h3>아직 게시물이 없습니다.</h3>
{% endif %}
{% endblock %}